version: '3.8'

services:
  backend:
    volumes:
    secrets:
    command: /bin/bash -c "export PYTHONPATH=/app && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
    expose:
      - 8000
  frontend:
    expose:
      - 80

  tester-backend:
    restart: "no"
    deploy:
      mode: global
  tester-frontend:
    restart: "no"
    deploy:
      mode: global